### ISSUE TITLE
USDS logo is a bit blurry on a retina display

### ISSUE THREAD

**Issue by konklone** [usds/playbook#112]
On my Macbook Pro's retina display, the USDS logo is a touch blurry:

![blurry on retina](https://cloud.githubusercontent.com/assets/4592/5869330/83ba4dd4-a285-11e4-8552-e2750d47db73.png)

I'm not totally sure what the best practices are in providing 2x images for retina display, or letting the browser size it or whatever, but wanted to at least flag it.

**Comment by rypan** [comment]
@mollieru has a vector version of it - so I don't think it should be too hard to get a 2x version of it!

**Comment by mollieru** [comment]
The updated design proposed in https://github.com/WhiteHouse/playbook/issues/134 should resolve this.

**Comment by cew821** [comment]
@mollieru @konklone can someone with a fancy computer verify that #161 fixed this?

**Comment by konklone** [comment]
Yes, it did:

![image](https://cloud.githubusercontent.com/assets/4592/10089239/92ce0864-62de-11e5-9eb2-1315665cac6b.png)

Thanks for fixing it!
