### ISSUE TITLE
Create a clear standard for identifying people (~OpenID)

### ISSUE THREAD

**Issue by nichbarry** [usds/playbook#117]
Were social security numbers were created to track social security benefits? (or maybe they were created to keep the gov safe from society [it is really the governments security {who's to say government isn't part of society? We are all secured by ss}]). Or perhaps create a first come first serve unique government ID. Make it a requirement; you only get one so choose wisely!

**Comment by nichbarry** [comment]
Would be interesting if you could have a personId and a botId to distinguish persons from bots

**Comment by cew821** [comment]
Thanks for the suggestion!
