### ISSUE TITLE
Redo infrastructure

### ISSUE THREAD

**Issue by nichbarry** [usds/playbook#119]
Physical infrastructure needs an overall overhaul. Seems like everyone has "cables" (like the cable company cables [CAT5?]) in their houses so that may be a good place to start. Build an infrastructure that can support:

1) Distributing discrete materials: plastics and metals should be delivered through pipes and tubes much like water is today. This would allow 3D printing
2) Individualized power plans: get everyone off the grid so the government can spend more time investing in new technologies (like #1 [weren't the telephone poles holes dug by slaves? {that's what I vaguely remember learning as a child...maybe it was BS |I have a BS|}])
3) Public internet: trade your privacy for free internet (private underground lines will be built [or you all could just get out of Verizon/AT&T's bed {they would need a restructure shortly thereafter}])

Why are these important to the digital playbook? 1 because 3D printing and 2 because web of things and 3 because the internet

**Comment by cew821** [comment]
Thanks for the suggestion @nichbarry
