### ISSUE TITLE
TechFAR: Vet a pool of contributors, recruit on a sprint by sprint basis; be tough

### ISSUE THREAD

**Issue by nichbarry** [usds/playbook#124]
I have always liked the idea of having a bullpen of professionals to choose from who are experts. Ideally, some of them would be salaried floaters *+team members+* who create self forming agile teams to solve the bigger quick wins that they see through experience / over time. So you have a grab bag of experts, who you know are not criminals, they've been "onboarded" and are cleared to work on certain levels (they have a clearance level and a skill level)...they get poked to work on projects, if they have the bandwidth they go for it. There are strict deadlines and an incremental daily deliverable. There is no room for buddy  buddy with the project manager; you either did it or you did not. You get paid daily in the currency of your choosing and yah that's it

**Comment by cew821** [comment]
thanks for the idea!
