### ISSUE TITLE
PlayBook-6 Prioritize Not Assign Tasks

### ISSUE THREAD

**Issue by wamack** [usds/playbook#128]
Suggesting rewording initial paragraph and checklist to indicate the product owner has the authority to "prioritize tasks and work elements" not to assign them.  Rationale: The product owner shold be concerned with what work is being done and not with who is doing the work.

**Comment by cew821** [comment]
Thanks for the suggestion! I think this is a little too granular for the play, but if you had a specific wording change to suggest, we would consider it. Thanks again!

**Comment by deffenda** [comment]
Bringing this thread back.  @wamack is exactly correct.  The product owner has the responsibility of prioritizing work, the product backlog and the vision of the product.  

What the playbook says about the Product Owner is exactly wrong.  The Product Owner does NOT assign tasks or NOR manages/decides the technical implementation details.  These latter two items are managed by a self-organizing and self-managing team.  The Product Owner should be informed, perhaps consulted, but teach is accountable and responsible for tasks and technical implementation.
