### ISSUE TITLE
Add a favicon to the Playbook so that it is easier to find amongst many open browser tabs.

### ISSUE THREAD

**Issue by jtag** [usds/playbook#132]

**Comment by mollieru** [comment]
@cew821 not sure if this is going to work, but let's give this a shot: 
![usds-favicon](https://cloud.githubusercontent.com/assets/3680494/8234319/24886b6a-15a9-11e5-98b3-eed65ed94d40.png)

**Comment by cew821** [comment]
I'm thinking of using the one Noah proposes in #88 

@mollieru can you take a look at #88?

**Comment by mollieru** [comment]
That is pretty hard to see when it's shrunken down to favicon size. 

What about this one which we're using for the web design standards favicon? USA? 

https://pages.18f.gov/usfwds/assets/img/favicons/favicon.ico

cc @noahmanger

**Comment by cew821** [comment]
@mollieru can you take a look at this again? Wound up implementing #88 in the recent design update. Do you still think the checkbox is too hard to read? 

Also wondering if we should add the same header and favicon as the Web Design Standards?

**Comment by cew821** [comment]
Closing this since there is now a Favicon. If there's a desire to change it, we can discuss in a new PR.
