### ISSUE TITLE
Improve SEO so that playbook appears in first page of search results

### ISSUE THREAD

**Issue by onezerojeremy** [usds/playbook#133]
I can never remember the URL and searching for "digital services playbook" does not produce a search result directly linking to the actual text of the playbook. 

there is a search result to this repo, but I suspect that will confuse many folks unfamiliar with github. 

![screen shot 2015-05-17 at 9 23 07 am](https://cloud.githubusercontent.com/assets/474916/7670539/ca96b54e-fc76-11e4-99df-0336ffbbce1b.png)

**Comment by cew821** [comment]
Yeah, I am bothered by that as well. I'd love suggestions from anyone with experience dealing with this issue (i.e. Google result points to GitHub repo vs. the content website associated with that repository). I am definitely not an SEO expert!

**Comment by neilmartis** [comment]
@cew821 @onezerojeremy I know of a company that can help

**Comment by cew821** [comment]
Happily, our SEO has improved so I don't think is an issue any more. Thanks all!

![image](https://cloud.githubusercontent.com/assets/1237498/15904335/9d85a2f6-2d7e-11e6-9410-bf1cfb6e6bc9.png)
