### ISSUE TITLE
Make the hover style of the USDS logo less ugly

### ISSUE THREAD

**Issue by kimballce** [usds/playbook#134]
![image](https://cloud.githubusercontent.com/assets/8903924/8175340/1d730c0c-13b7-11e5-8c0a-39b39e3584ee.png)
When I hover over the USDS logo, I see a boxy off-white blue. Would be great to clean this up.

**Comment by cew821** [comment]
cc @mollieru -- any ideas for different hover state?

**Comment by mollieru** [comment]
Good Feedback @kimballce -- like your designer eye :)

@cew821 what if we try swapping in the circle version, which works better on dark background and give is a lower opacity on hover?

![usds-logo-circle](https://cloud.githubusercontent.com/assets/3680494/8233876/b3f52f34-15a6-11e5-97f3-edb5748bcdb2.png)

**Comment by rypan** [comment]
Or is it possible to reveal/hide the rays on hover?

Or like @mollieru suggests - bump up/down the opacity on hover? (But in this case...use the current image...and the default state is like .8 opacity...and on hover it goes to 1)

**Comment by mollieru** [comment]
We've stopped using the burst all together (lots of feedback about how it was hard to use in a bunch of contexts -- iterating!).

**Comment by kimballce** [comment]
@mollieru I say let's try the circle!

**Comment by mollieru** [comment]
@cew821 lmk if you need a different file format for your next update.
