### ISSUE TITLE
How-to for direct use of open source

### ISSUE THREAD

**Issue by kastork** [usds/playbook#155]
Many agencies and government educational and research institutions develop software in-house that would benefit by having OSS libraries as dependencies, or who use open source tools directly to do work (using something like R, for example).  In some locations, local policies are ignorant about open source and those local authorities activate "the 'no' machine" when anyone tries to use things that are covered by OSS licenses.  "We don't understand this, and we don't have the time or resources to get educated about it, so, no, we won't let you do that"

It would be extremely useful to have a guide-book to assist local authorities to craft "yes" policies that they can have confidence in as being compliant with federal copyright law.

For example: do I need a Contract in order to use R in my analysis shop?  Can our code depend on a GPL library and then be distributed to the public? (how about just to other agencies?).  What steps must I take to do that correctly?  Do Ineed a DTIC release statement?

**Comment by johnvndnbrk** [comment]
Hi Kastork - I am looking at 10+ open source program modules I will be using on my current assignment.  We most certainly can develop software that depends on OSS with GPL Licenses.  I would recommend searching the TRM compliance website with what software you have in mind to use to check if it has been approved.  Any requests for software not on their approved list most likely would need to be approved the your projects COR for submittal to the review board. R for statistical program is on their approved list. Good luck

**Comment by kastork** [comment]
@johnvndnbrk my local agency views any and all "license agreements" including gpl, mit, and Apache as things which must be run through a contracting process in order to be "agreed to".  Please explain how to enter into a contract with "Linux" -- who on the "Linux side of the contract"is going to sign?.  I'm not saying  OSS is impossible, I'm saying that there are some places in government that simply don't get it, and just need to be educated about it so that local policies can be crafted that help people get to work instead of preventing people from getting to work.  My suggestion here is to create a "how to" for someone like me who needs to get permission to use OSS in an environment where nobody at the local level gets it.

**Comment by johnvndnbrk** [comment]
Hi Kastork - I mentioned in my previous post that there is a service offered by VA-One for public consumption which I referred to as TRM.  In your first post you asked if you needed "a Contract in order to user R".  So I to the time to look up this technology to see if the compliance board has approved the use of this technology via TRM.  They have, in fact, approved "R for statistical programs".

Your follow-up post is asking what contractual obligations does your agency have, stating that you must have agreement with the government to proceed.  At this stage you are not agreeing solely on the use of OSS but offer a design approach you believe will meet the needs of the contract you are bidding on.  Unfortunately, I am only a software developer so the point where I come into the picture is after an agreement has been reached.  My point was that you can use OSS when developing software solutions.  I use many OSS technologies, so this is what I was referring to.  I would think you are asking questions regarding the bidding process, and I am sorry to say that I don't know this process.  Best of luck and my apologies for the confusion.

**Comment by MarinaMartin** [comment]
@johnvndnbrk This playbook is for the entire federal government. The TRM only applies to VA.

**Comment by johnvndnbrk** [comment]
Ah ... I have only worked for the VA/VBA.  Thanks for the clarification.  Any ideas on what might help Kastork? Thanks!

**Comment by MarinaMartin** [comment]
@kastork Depending on what agency you're at, you might be able to find help. There is also a best-practices group where you can seek help here: https://github.com/government/best-practices/issues. And while you might not work at VA, sometimes pointing to another agency that has already done or approved something is all it takes... so definitely check out our TRM to see if we have approved something you want to use. Our entire electronic health record system used in hospitals is open source, so VA can be a bit more comfortable/familiar with those approvals.

**Comment by jqnatividad** [comment]
@MarinaMartin was just looking for https://github.com/government/best-practices, in light of the recent Federal Open Source Policy, and I can't find it.  Do you know where the repo is currently hosted? Thx in advance!

**Comment by camfindlay** [comment]
@jqnatividad the repo for that site is private and part of a community of practice for government github/open source users.
You can access if you have a known government email address tied to your github account. 

See https://github.com/government/welcome#government-community-on-github

Hope that helps 👍

**Comment by cew821** [comment]
@kastork I recommend taking a look through the Department of Defense's excellent Open Source Software policy. DoD has been a pioneer in codifying the use of open source software in government, and if DoD http://dodcio.defense.gov/Open-Source-Software-FAQ/ 

In addition to this policy, DoD published a memo describing the benefits of using open source: http://dodcio.defense.gov/Portals/0/Documents/OSSFAQ/2009OSS.pdf

The CFPB has also released a detailed policy regarding the use of open source software: https://cfpb.github.io/source-code-policy/

Hope this helps! Closing the issue for now.
