### ISSUE TITLE
Thoughts on content

### ISSUE THREAD

**Issue by johnvndnbrk** [usds/playbook#168]
Hello,
I am in agreement with just about all that would said on the playbook.cio.gov.  As a software developer for VA in a contractor capacity, standards or compliance material are always of interest to me.

I have been benefitting from HTML 5 standards with respect to usability and its positive impact with assistive technologies.  My works needs to be 508 compliant, of course, and I am thrilled with how HTML5 has made this easier to realize.

I use Microsoft technologies for a major part of my software development.  Using NuGet, Bower, and NPM I have discovered the world of open source and cannot say how much this has helped in so many areas of the SDLC.  If I plan on using anything from a JS library to a DI container my first top is to the TRM compliance software site so I can confirm it has been approved and for what version.

If you are looking for additional assistance with this initiative, please let me know.  I have been developing mission critical systems for 20 years and continue to find developing software a pleasure.

**Comment by jeugster** [comment]
Here is the TRM Page for reference. Thanks for leading me to it!
[](http://www.va.gov/TRM/TRMHomePage.asp#)

**Comment by MarinaMartin** [comment]
If you're having challenges getting modern open source technologies on the TRM please reach out to me directly. I don't want them caught in a black hole of paperwork.

**Comment by johnvndnbrk** [comment]
That is a very generous offer!  Thank You!  I need to be careful with using proper channels of communication.  Also, I would hate to become a burden unless there is something I could assist you with *smile*.  I would be interested to know if Automapper is being used.  I would say about 90% of OSS I have a preference for or background with has been approved.  Thank you again, I appreciate it!

**Comment by MarinaMartin** [comment]
@johnvndnbrk Getting the right tools approved for use at VA is not a burden - it's my job! Happy to help.

**Comment by julie-s-harvey** [comment]
There are over  800 open source entries on VA's TRM, and growing.  That's about 22% of our database.

**Comment by johnvndnbrk** [comment]
Also, the versions of open source software are either the latest stable version or close to that.  From what I see the VA has embraced open source but do so after a review of the software, and then continually thereafter.  If the open source software has an active community and broad acceptance, there is a good chance that this software is on the TRM list of approved software.

**Comment by johnvndnbrk** [comment]
@MarinaMartin - Once again, thank you for your assistance.  I reviewed the Automapper OSS and unfortunately they seem to work with bleeding edge technology from Microsoft.  They are using DNX SDK rc-final and C# v6.  They are also using psake, 7-zip, xunit, Rhino Mocks, etc. and other dependencies which most likely need to be reviewed as well.  I will keep an eye out for this but for the moment even I wouldn't be comfortable using this for production applications.  I appreciate your support! John

**Comment by cew821** [comment]
Thanks for the feedback! I'm going to close this issue, but glad you could connect up and find the content useful. Let us know if you have any suggestions.
