### ISSUE TITLE
Case studies

### ISSUE THREAD

**Issue by tjpeeler1** [usds/playbook#185]
@jonmost We talked at GoodGovUX about examples of case studies from some work we've done at the FTC. 

1. 18F recently wrote a case-study-esque [blog post about the redesign of identitytheft.gov](https://18f.gsa.gov/2016/05/24/the-user-centered-redesign-of-identitytheft-gov/). I didn't work on the redesign, but can put you in touch with my colleagues who did.

1. A few years ago we redesigned our [main consumer site](https://www.consumer.ftc.gov/). This redesign involved changing our content strategy to writing for digital first.

tpeeler@ftc.gov

**Comment by jonmost** [comment]
This is great thanks!
