### ISSUE TITLE
http://playbook.cio.gov/ is down

### ISSUE THREAD

**Issue by wslack** [usds/playbook#198]
cc @alex and @cew821 

h/t @thecapacity for noticing https://playbook.cio.gov/techfar/ was down, which led me to this issue.

<img width="355" alt="screen shot 2016-11-02 at 11 03 58 am" src="https://cloud.githubusercontent.com/assets/10016577/19934161/1760734a-a0ec-11e6-957a-d4e5ac276cf2.png">

**Comment by alex** [comment]
Looks up for me.

**Comment by alex** [comment]
Thanks for the report though, I suspect at most this was a very short lived outage.

**Comment by wslack** [comment]
@alex yep, back up here just now. Whatever it was, it lasted 10 minutes, but maybe not much more.
