### ISSUE TITLE
Just Found This Amazing Resource and Can't Wait to DIVE IN...

### ISSUE THREAD

**Issue by DarrenBatesLLC** [usds/playbook#203]
I just scanned the Plays and found so much incredibly valuable information relative to building and refining sustainable, accessible and inclusive Smart Cities that ensure NO CITIZEN IS LEFT BEHIND.   

Before I go on, let me briefly introduce myself: My name is Darren Bates, and I'm the founder of Darren Bates LLC. **We make accessibility and inclusion relevant, user-friendly and easy to incorporate into your Smart City platform.**  

Darren Bates LLC is a boutique consulting firm and global resource for inclusive and accessible Smart Cities. We empower Smart Cities, government, and private industry—at all stages of growth—to build accessible and inclusive digital societies that ensure no citizen is left behind. We support people-centric urban design and the global mandate calling for municipalities to design and build Smart Cities for human diversity and social inclusion.

As I write this — our website (www.darrenbatesllc.com)  is undergoing a major UPGRADE.  Our new site will include for the first time: **The Smart Cities Library — our continuously expanding online library of Smart City solutions, best practices, articles, e-books, and other useful resources curated from thousands of academic, public, and national libraries and periodicals from around the world.**

We plan to launch the new site late June 2017. Right now--if you go to www.darrenbatesllc.com - you can fill out a 1 min contact form to be notified when we GO LIVE.  I encourage everyone on this project to fill out the form - I will personally reach out to you, and hopefully, we can find innovative ways to partner collaborate and expand the capacity and synergy of the Bostom Smart City Playbook!

with my very best,
Darren Bates

Website: www.darrenbatesllc.com
Twitter: @DLBLLC 
Facebook: darrenbatesllc
Medium: @darrenbatesllc

Building a Culture of Access and Inclusion in the Modern Workplace™

**Comment by DarrenBatesLLC** [comment]
My apologies if I did something wrong —or out of the proper mode. I DO NOT KNOW GITHUB and just wanted to say what I had to say — I think The Boston Smart City Plays are the vanguard of resources and checklist and roadmaps and I wanted to say that much.

Thanks.





Darren Bates
President/Global Accessibility & Inclusion Strategist

Darren Bates LLC
2407 South Congress Ave, Suite E136
Austin, TX 78704
Mobile/Text: 512.289.3636
Email: DLB@darrenbatesllc.com <mailto:DLB@darrenbatesllc.com>

Website: www.darrenbatesllc.com <http://www.darrenbatesllc.com/>
Twitter: @DLBLLC <https://twitter.com/DLBLLC> 
Facebook: darrenbatesllc <http://www.facebook.com/darrenbatesllc/>
Medium: @darrenbatesllc <https://medium.com/@darrenbatesllc/latest>

Recent Blogs:
Recent Blogs:
▪ Adding Accessibility and Inclusion into Austin’s Smart Cities Strategic Roadmap <http://bit.ly/2lswa6V>
▪ Adding Universal Design Techniques to Keep Austin Beautiful <http://bit.ly/2mAoLDL>
▪ Disability: An Upside for Everyone in Unifying Smart City Design <http://bit.ly/2kjdSrc>
▪ Smart Cities Built for Everyone | Innovations in Accessible & Inclusive Urban Design <http://bit.ly/2kjfZeB>
▪ The Secret Sauce of a Successful Smart City <http://bit.ly/2jyWj1X>
▪  <http://www.darrenbatesllc.com/newsroom/a-smart-city-is-a-connnected-city-and-a-connected-city-is-an-inclusive-city>A Smart City is a Connected City, A Connected City is an Inclusive City <http://bit.ly/2kmN1L8>
▪ The Power of Words: Respect, Equality, Diversity and Inclusion <http://bit.ly/2kmJexp>
▪ Top 10 Ways to Market to People with Disabilities and Boost Your ROI <https://www.linkedin.com/today/post/article/20140703000007-11466134-top-10-ways-to-market-to-people-with-disabilities-and-boost-your-roi?trk=mp-author-card>

Building a Culture of Access and Inclusion in the Modern Workplace™

**Comment by charwo** [comment]
Good luck with your project!

**Comment by DarrenBatesLLC** [comment]
It's about YOUR PROJECT! Is the Boston plays still live and receiving info ?


Darren Bates
President/Global Accessibility & Inclusion Strategist

Darren Bates LLC
2407 South Congress Ave, Suite E136
Austin, TX 78704
Mobile/Text: 512.289.3636
Email: DLB@darrenbatesllc.com

Website: www.darrenbatesllc.com
Twitter: @DLBLLC 
Facebook: darrenbatesllc
Medium: @darrenbatesllc

Recent Blogs:
▪ Disability: An Upside for Everyone in Unifying Smart City Design
▪ Smart Cities Built for Everyone | Innovations in Accessible & Inclusive Urban Design
▪ The Secret Sauce of a Successful Smart City
▪ A Smart City is a Connected City, A Connected City is an Inclusive City
▪ The Power of Words: Respect, Equality, Diversity and Inclusion
▪ Top 10 Ways to Market to People with Disabilities and Boost Your ROI
	

Building a Culture of Access and Inclusion in the Modern Workplace™

**Comment by raquelromano-gov** [comment]
Hi Darren,
I believe you are looking at https://github.com/monum/playbook, which is a fork of https://github.com/usds/playbook (this repository, which is not related to the City of Boston). You likely want to direct your comments to the folks at the Mayor's Office of New Urban Mechanics once your library is available on your website: https://github.com/orgs/monum/people
Good luck!

**Comment by DarrenBatesLLC** [comment]
Well -that explains it ! Thank you so much for the information I will definitely let that office know when the smart cities libraries goes live!

 Would you like to be notified as well?   Is there something that I might be able to help you with that you help me with. I often work in Washington DC a-- I used to work as a consultant for the Office  of Disability Employment Policy and  Social-Security -- and more --but now with the new administration -- well let's just say those opportunities are not as bright anymore..

If  you'd like to chat and discuss possible alignment -I'd  be happy to set something up. 

Again thank you so much for putting me in the right direction and for the support.  



Darren Bates
President/Global Accessibility & Inclusion Strategist

Darren Bates LLC
2407 South Congress Ave, Suite E136
Austin, TX 78704
Mobile/Text: 512.289.3636
Email: DLB@darrenbatesllc.com

Website: www.darrenbatesllc.com
Twitter: @DLBLLC 
Facebook: darrenbatesllc
Medium: @darrenbatesllc

Recent Blogs:
▪ Disability: An Upside for Everyone in Unifying Smart City Design
▪ Smart Cities Built for Everyone | Innovations in Accessible & Inclusive Urban Design
▪ The Secret Sauce of a Successful Smart City
▪ A Smart City is a Connected City, A Connected City is an Inclusive City
▪ The Power of Words: Respect, Equality, Diversity and Inclusion
▪ Top 10 Ways to Market to People with Disabilities and Boost Your ROI
	

Building a Culture of Access and Inclusion in the Modern Workplace™
